kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s-minio-config
  namespace: dev
data:
  SERVICE_NAME: "k8s-minio"
  NODE_ENV: "development"
  NODE_PORT: "6767"
  HOST: "0.0.0.0"
  BASE_PATH: "/api"
  TZ: "Asia/Bangkok"
  ENCRYPTION_KEY: "7nB3rrON3PrDR4y4s6liBNC4M4P562kg"
  PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----

    MIIJKwIBAAKCAgEA555mpYWb7/DUefmPIuJcvliCHFYGp0EFGdSmW8B1+QgMGxSY

    EioCCx50QCPyiFebRB+w+esNLL+JVw9m1RGrvz/PKt+6p9aTKCxGLgnJGAw1cLh3

    aj2OQZzbODmjffosWCCMgEWlFCCQAUsTz/4ijAwek92/5efQeOyTWHi1DcHILD5R

    0srrgVCHnD3Xgm9li6ndbi25sBTwzB0n26m3BOjxoSE8HT8eFQlu+Rt88of4Zm0u

    UpUPwogIzASak6UOEdGx//J6Cr1F4X5cG+opL323yQ/xFXyamaRpIkKuMW54CnzQ

    CSoYpeROxpR6HV9icg+0y4RxmcejV9SPlMpeAluaAjmM1UW+1oNPbQuYczVySpym

    FIhHVAXiEwrmgabubXhQhnWR5ALgt3qsBuREdi6N7P6JOV54WWHL+N71/yr/a0xU

    JZ3GhvfC/mGBYeNVQJKIaERVbnMSJBoBscI7B4UIZrlaPavpXj5frY443fCLChrM

    C+EgOVlNbY7t+kiTpaVat0C1LCluA/iI+wpUlZ7n5bDLBg1d+XuWAUiz1vRgSyV0

    sE1vfSPHCw9HCJRHB+0rDwHARetZeNhQfXFF0e0L6V1dUL+lOK8F1VKTXRYkTXMu

    aLRGcNGYy5AyvRLx9XFfEQpVyMbVg0OWm677k4izrqck9+/333rd6Se33n0CAwEA

    AQKCAgEAzYPwongOKHXxopU8W4CtODxCnq/6UVfRFd1pC0qXozNvwmugj6V0kLci

    AXOkFTRe0bCpEOhulUEStQw2e2KlmRoeUXWZIqmzg1bdoqYOJ+dVV8JmOv+JhVCP

    97C1D+f2hu/Cm2Kwmk5WWL9sQgbGUqvCSgPd7Tqm8VVBXKQmSqGiYxec9MQW+XQi

    EBGTcuozGRzNHKE3/TRngUVxg2hwu8uR8x4RQAYsRBBNxn2MfYsGbqP8EUywYjTg

    UV7YZZ9z/32oSmm1vme5ZN8BDcfVaY1MkPwzN5SLfT60BrFR7QyPOQcMdMVEf5Y4

    C93dCMkFCh5Dlr3bKs9IcXtrN2PkytRdEAM+C7AGn3QOnQ8RSCjbeB2X7pflP4zS

    gh1Hy8dZWMusbS3ykP8Do+swN3SQhjxWuUyjeYGUMac+FwjEFrhyB+hwKYmK/d4q

    5jqkfzrbR3JBv0s1ExRHu1OsJ/x+lD5hEtjY9u8BLrPNpXsYwq//eSiCIsDQe51+

    oLkluiMRWms0l/Cm2GUR7Ob5E8VLr6C4HeiJiWOxoPedglM/TH6YUrLIbJLxxvPm

    PdzkFTf3OQItqf/+y5jWKX6x6RE6WoYjCuzxLB8IBk9Q4cJLVj4PvKRwGvkRhyJI

    sT0BTBQVyezH6m/HfizgZpzJPN9xRLRwk2TU66OMfnhaR/i/7AUCggEBAPy5xfwG

    85D3GlrHbJUF20Vog0L6S/jP8DDowPjSMPn2//0foWfvXRxlAEqGWSmMok++BwBM

    O5MRDpIKLeS3vdBOGz/UHLJ6rve3zeDkvIbTLz6AcBI4mK5nWHp2nzpNiTHNAG7H

    vZg1B0EWttjZRJlUbClPQtdsEHDah1Nem7JIgXhMUp4gcLQ2hAWyRtDN5JMHsH2O

    g2K0HOFe1EKlskBoZ+BmJWsQSJEsoVoft7+49c6j8BbUVKYYRPR4KeRkHyeEdgm/

    DcGzXjgWC2jRJ4/QGOYcnHH/t3R8KLY5Qdf8xDaQBxpOfiBy2ej1pXbnpU6iQnc+

    nh9Pw1qeSPJcqisCggEBAOqenw3AxZ+WBZGQ8mPsQBoJv33pKzIHDuAbbh1JwBkY

    ldv77TEH3m8JUR7qdcSUUt1ykzFFZRGQlKeDE3eJk7lUpX3bABW+4Rg9bVg54nSS

    yVJD01pTiYJtFdKfEtzYoKeZ8EvDAHL4bFPa9z4HkQaWnRAb2EUrXl/aKfRoVk/F

    OYHamDmU+ENk6hSYijCJ+d9UadTf9MPpKzNYGeansqXZ0GxDcHo6kdHj5u+PPtnY

    OUj3vY2DjUBMecFypHFLdgasHOMM1tSG5tDoAmzR7W0NAxcPzUQppDGYd49tcDxq

    YMAZTiGOFjiP8jh4wt4Ey3H+ecebcE30jCcc5PbCjfcCggEBAIgm4VW8vP1tUoJz

    i7jhNdc3zfeIduNtyv3edw/V1VLlUdYhc0hWOThx5W1A4coznMIPIyBy8WlyuAHP

    gBgHMTiGy8FgWbGBzL9iA4VUVYjhP0OR2E7ItODIhm87dt7nJLFyuvfznd3hO65C

    OXGr43wjcj3zGJSMAHN8F4m/n2u2CiIwJBZSbcV41TloaSRWt/zKGLgbzgaf+Csm

    dn4NXHG8jbHj9eavGBk2DRtLmSet0qdnxJHYBF6TFpsKHa+QjQQyJZFsn1Gqe2kF

    31Gx1Hly5+cYpOP5mvEjbp91S1a8M00d3OW8QdDjbyhFJsZfV7x8SAiL8I3338vz

    GGORro8CggEBAOH9A8tlgXWkNZzu9usUpvHtrcuECp1XexaWlUwUu7nwmniYgvGV

    WMWvPbn/sIw3KlIviGQPKbjvgKCRevDLTcVYKUe+6KgJghutH2O57czHjq90sWHx

    0SQWGs0TeEHNT4Hgnzr6i7YyX3WuFjRjaWflL0hS6dBGY9MD+yF2Vpzjpe7UNYhR

    W4je7TIFdCYo4MwjLQVk6wjB0WDVXa10nnluAnolw3OYctivIsRhP/LpeNQ1/RkQ

    O8BRaX3SBV8zhm4K3pA8z7lKb42NzLgwxPcjb3SJPfiH+6Xh7Ff03AT1mleuiDl9

    +R1mWbPXbiwYhjY5HegMavJLuav7AvhEkiUCggEBAO0H7ukZMuHLE52ahLwROHJr

    eOfhAHIoq/q+Fo+DyKxpc0ux7Lz7icmVlSaJHolfmTOgrR/GmHggdBmsINL47IhZ

    s66EDlFbHrryAYl1UUbHGGfg4Zhlac9zjpc61UqLS1Mopp/OOYgRdbWLDB+fTdfy

    r+ti4gWVRlORnhE/zj2piovLVkRzLSUeGleezGDQWg5r/z3T3IL+HFpXKHZnAZJ8

    blpJeJDO0W5yUk1kfiv6lg3k734RGjiBaGCvWZ51lv4JybhQzeDxI89I/xspgk3i

    F7/8tunw4dC1koBjhOUfn3vt1uzH7N6GuhKgQ+kpV7b1tLkjZhXwDYVxdbWmRcA=

    -----END RSA PRIVATE KEY-----"
  PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----

    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA555mpYWb7/DUefmPIuJc

    vliCHFYGp0EFGdSmW8B1+QgMGxSYEioCCx50QCPyiFebRB+w+esNLL+JVw9m1RGr

    vz/PKt+6p9aTKCxGLgnJGAw1cLh3aj2OQZzbODmjffosWCCMgEWlFCCQAUsTz/4i

    jAwek92/5efQeOyTWHi1DcHILD5R0srrgVCHnD3Xgm9li6ndbi25sBTwzB0n26m3

    BOjxoSE8HT8eFQlu+Rt88of4Zm0uUpUPwogIzASak6UOEdGx//J6Cr1F4X5cG+op

    L323yQ/xFXyamaRpIkKuMW54CnzQCSoYpeROxpR6HV9icg+0y4RxmcejV9SPlMpe

    AluaAjmM1UW+1oNPbQuYczVySpymFIhHVAXiEwrmgabubXhQhnWR5ALgt3qsBuRE

    di6N7P6JOV54WWHL+N71/yr/a0xUJZ3GhvfC/mGBYeNVQJKIaERVbnMSJBoBscI7

    B4UIZrlaPavpXj5frY443fCLChrMC+EgOVlNbY7t+kiTpaVat0C1LCluA/iI+wpU

    lZ7n5bDLBg1d+XuWAUiz1vRgSyV0sE1vfSPHCw9HCJRHB+0rDwHARetZeNhQfXFF

    0e0L6V1dUL+lOK8F1VKTXRYkTXMuaLRGcNGYy5AyvRLx9XFfEQpVyMbVg0OWm677

    k4izrqck9+/333rd6Se33n0CAwEAAQ==

    -----END PUBLIC KEY-----"
  PARTNER_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----

    MIIJKwIBAAKCAgEA555mpYWb7/DUefmPIuJcvliCHFYGp0EFGdSmW8B1+QgMGxSY

    EioCCx50QCPyiFebRB+w+esNLL+JVw9m1RGrvz/PKt+6p9aTKCxGLgnJGAw1cLh3

    aj2OQZzbODmjffosWCCMgEWlFCCQAUsTz/4ijAwek92/5efQeOyTWHi1DcHILD5R

    0srrgVCHnD3Xgm9li6ndbi25sBTwzB0n26m3BOjxoSE8HT8eFQlu+Rt88of4Zm0u

    UpUPwogIzASak6UOEdGx//J6Cr1F4X5cG+opL323yQ/xFXyamaRpIkKuMW54CnzQ

    CSoYpeROxpR6HV9icg+0y4RxmcejV9SPlMpeAluaAjmM1UW+1oNPbQuYczVySpym

    FIhHVAXiEwrmgabubXhQhnWR5ALgt3qsBuREdi6N7P6JOV54WWHL+N71/yr/a0xU

    JZ3GhvfC/mGBYeNVQJKIaERVbnMSJBoBscI7B4UIZrlaPavpXj5frY443fCLChrM

    C+EgOVlNbY7t+kiTpaVat0C1LCluA/iI+wpUlZ7n5bDLBg1d+XuWAUiz1vRgSyV0

    sE1vfSPHCw9HCJRHB+0rDwHARetZeNhQfXFF0e0L6V1dUL+lOK8F1VKTXRYkTXMu

    aLRGcNGYy5AyvRLx9XFfEQpVyMbVg0OWm677k4izrqck9+/333rd6Se33n0CAwEA

    AQKCAgEAzYPwongOKHXxopU8W4CtODxCnq/6UVfRFd1pC0qXozNvwmugj6V0kLci

    AXOkFTRe0bCpEOhulUEStQw2e2KlmRoeUXWZIqmzg1bdoqYOJ+dVV8JmOv+JhVCP

    97C1D+f2hu/Cm2Kwmk5WWL9sQgbGUqvCSgPd7Tqm8VVBXKQmSqGiYxec9MQW+XQi

    EBGTcuozGRzNHKE3/TRngUVxg2hwu8uR8x4RQAYsRBBNxn2MfYsGbqP8EUywYjTg

    UV7YZZ9z/32oSmm1vme5ZN8BDcfVaY1MkPwzN5SLfT60BrFR7QyPOQcMdMVEf5Y4

    C93dCMkFCh5Dlr3bKs9IcXtrN2PkytRdEAM+C7AGn3QOnQ8RSCjbeB2X7pflP4zS

    gh1Hy8dZWMusbS3ykP8Do+swN3SQhjxWuUyjeYGUMac+FwjEFrhyB+hwKYmK/d4q

    5jqkfzrbR3JBv0s1ExRHu1OsJ/x+lD5hEtjY9u8BLrPNpXsYwq//eSiCIsDQe51+

    oLkluiMRWms0l/Cm2GUR7Ob5E8VLr6C4HeiJiWOxoPedglM/TH6YUrLIbJLxxvPm

    PdzkFTf3OQItqf/+y5jWKX6x6RE6WoYjCuzxLB8IBk9Q4cJLVj4PvKRwGvkRhyJI

    sT0BTBQVyezH6m/HfizgZpzJPN9xRLRwk2TU66OMfnhaR/i/7AUCggEBAPy5xfwG

    85D3GlrHbJUF20Vog0L6S/jP8DDowPjSMPn2//0foWfvXRxlAEqGWSmMok++BwBM

    O5MRDpIKLeS3vdBOGz/UHLJ6rve3zeDkvIbTLz6AcBI4mK5nWHp2nzpNiTHNAG7H

    vZg1B0EWttjZRJlUbClPQtdsEHDah1Nem7JIgXhMUp4gcLQ2hAWyRtDN5JMHsH2O

    g2K0HOFe1EKlskBoZ+BmJWsQSJEsoVoft7+49c6j8BbUVKYYRPR4KeRkHyeEdgm/

    DcGzXjgWC2jRJ4/QGOYcnHH/t3R8KLY5Qdf8xDaQBxpOfiBy2ej1pXbnpU6iQnc+

    nh9Pw1qeSPJcqisCggEBAOqenw3AxZ+WBZGQ8mPsQBoJv33pKzIHDuAbbh1JwBkY

    ldv77TEH3m8JUR7qdcSUUt1ykzFFZRGQlKeDE3eJk7lUpX3bABW+4Rg9bVg54nSS

    yVJD01pTiYJtFdKfEtzYoKeZ8EvDAHL4bFPa9z4HkQaWnRAb2EUrXl/aKfRoVk/F

    OYHamDmU+ENk6hSYijCJ+d9UadTf9MPpKzNYGeansqXZ0GxDcHo6kdHj5u+PPtnY

    OUj3vY2DjUBMecFypHFLdgasHOMM1tSG5tDoAmzR7W0NAxcPzUQppDGYd49tcDxq

    YMAZTiGOFjiP8jh4wt4Ey3H+ecebcE30jCcc5PbCjfcCggEBAIgm4VW8vP1tUoJz

    i7jhNdc3zfeIduNtyv3edw/V1VLlUdYhc0hWOThx5W1A4coznMIPIyBy8WlyuAHP

    gBgHMTiGy8FgWbGBzL9iA4VUVYjhP0OR2E7ItODIhm87dt7nJLFyuvfznd3hO65C

    OXGr43wjcj3zGJSMAHN8F4m/n2u2CiIwJBZSbcV41TloaSRWt/zKGLgbzgaf+Csm

    dn4NXHG8jbHj9eavGBk2DRtLmSet0qdnxJHYBF6TFpsKHa+QjQQyJZFsn1Gqe2kF

    31Gx1Hly5+cYpOP5mvEjbp91S1a8M00d3OW8QdDjbyhFJsZfV7x8SAiL8I3338vz

    GGORro8CggEBAOH9A8tlgXWkNZzu9usUpvHtrcuECp1XexaWlUwUu7nwmniYgvGV

    WMWvPbn/sIw3KlIviGQPKbjvgKCRevDLTcVYKUe+6KgJghutH2O57czHjq90sWHx

    0SQWGs0TeEHNT4Hgnzr6i7YyX3WuFjRjaWflL0hS6dBGY9MD+yF2Vpzjpe7UNYhR

    W4je7TIFdCYo4MwjLQVk6wjB0WDVXa10nnluAnolw3OYctivIsRhP/LpeNQ1/RkQ

    O8BRaX3SBV8zhm4K3pA8z7lKb42NzLgwxPcjb3SJPfiH+6Xh7Ff03AT1mleuiDl9

    +R1mWbPXbiwYhjY5HegMavJLuav7AvhEkiUCggEBAO0H7ukZMuHLE52ahLwROHJr

    eOfhAHIoq/q+Fo+DyKxpc0ux7Lz7icmVlSaJHolfmTOgrR/GmHggdBmsINL47IhZ

    s66EDlFbHrryAYl1UUbHGGfg4Zhlac9zjpc61UqLS1Mopp/OOYgRdbWLDB+fTdfy

    r+ti4gWVRlORnhE/zj2piovLVkRzLSUeGleezGDQWg5r/z3T3IL+HFpXKHZnAZJ8

    blpJeJDO0W5yUk1kfiv6lg3k734RGjiBaGCvWZ51lv4JybhQzeDxI89I/xspgk3i

    F7/8tunw4dC1koBjhOUfn3vt1uzH7N6GuhKgQ+kpV7b1tLkjZhXwDYVxdbWmRcA=

    -----END RSA PRIVATE KEY-----"
  PARTNER_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----

    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA555mpYWb7/DUefmPIuJc

    vliCHFYGp0EFGdSmW8B1+QgMGxSYEioCCx50QCPyiFebRB+w+esNLL+JVw9m1RGr

    vz/PKt+6p9aTKCxGLgnJGAw1cLh3aj2OQZzbODmjffosWCCMgEWlFCCQAUsTz/4i

    jAwek92/5efQeOyTWHi1DcHILD5R0srrgVCHnD3Xgm9li6ndbi25sBTwzB0n26m3

    BOjxoSE8HT8eFQlu+Rt88of4Zm0uUpUPwogIzASak6UOEdGx//J6Cr1F4X5cG+op

    L323yQ/xFXyamaRpIkKuMW54CnzQCSoYpeROxpR6HV9icg+0y4RxmcejV9SPlMpe

    AluaAjmM1UW+1oNPbQuYczVySpymFIhHVAXiEwrmgabubXhQhnWR5ALgt3qsBuRE

    di6N7P6JOV54WWHL+N71/yr/a0xUJZ3GhvfC/mGBYeNVQJKIaERVbnMSJBoBscI7

    B4UIZrlaPavpXj5frY443fCLChrMC+EgOVlNbY7t+kiTpaVat0C1LCluA/iI+wpU

    lZ7n5bDLBg1d+XuWAUiz1vRgSyV0sE1vfSPHCw9HCJRHB+0rDwHARetZeNhQfXFF

    0e0L6V1dUL+lOK8F1VKTXRYkTXMuaLRGcNGYy5AyvRLx9XFfEQpVyMbVg0OWm677

    k4izrqck9+/333rd6Se33n0CAwEAAQ==

    -----END PUBLIC KEY-----"

  S3_REGION: "us-east-1"
  S3_ENDPOINT: "http://minio.minio.svc.cluster.local:9000"
  S3_ACCESS_KEY_ID: "admin"
  S3_SECRET_ACCESS_KEY: "StrongPassword123"
  S3_BUCKET: "monpity"
  S3_FORCE_PATH_STYLE: "true"
